version: '3'
services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    environment:
      - TZ=Etc/UTC
      - CRON_MIN=1,31
      - ALL_PROXY=socks5h://${BRIDGE_IP}:1080
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    ports:
      - 8084:80
    restart: unless-stopped
networks:
  default:
    name: proxion-network
    external: true
