version: '3'
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    build:
      context: .
      dockerfile: Dockerfile.hardened
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      - ALL_PROXY=socks5h://${BRIDGE_IP}:1080
    ports:
      - "13378:80"
    volumes:
      - ${STASH_ROOT}/media/audiobooks/library:/audiobooks
      - ${STASH_ROOT}/media/audiobooks/podcasts:/podcasts
      - ${STASH_ROOT}/media/audiobooks/config:/config
      - ${STASH_ROOT}/media/audiobooks/metadata:/metadata
networks:
  default:
    name: proxion-network
    external: true
