version: '3'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - TZ=UTC
    volumes:
      - ${STASH_ROOT}/media/radarr-config:/config
      - ${MEDIA_MOVIES}:/movies
      - ${LOCAL_DOWNLOADS}:/downloads
    ports:
      - "7878:7878"
networks:
  default:
    name: proxion-network
    external: true
