services:
  tdarr:
    container_name: tdarr
    image: haveagitgat/tdarr:latest
    restart: unless-stopped
    environment:
      - TZ=UTC
      - PUID=1001
      - PGID=1001
      - serverIP=tdarr
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
    volumes:
      - ${STASH_ROOT}/media/tdarr-config/server:/app/server
      - ${STASH_ROOT}/media/tdarr-config/configs:/app/configs
      - ${STASH_ROOT}/media/tdarr-config/logs:/app/logs
      - ${MEDIA_MOVIES}:/media/movies
      - ${STASH_ROOT}/media/tv:/media/tv
      - ${STASH_ROOT}/media/tdarr-cache:/temp
      - ${MEDIA_MUSIC}:/media/music
      - ${MEDIA_MOVIES}:/media/video
      - ${STASH_ROOT}/I_Ingest:/media/ingest
    ports:
      - "8265:8265"
      - "8266:8266"
networks:
  default:
    name: proxion-network
    external: true
